version: '3.8'
services:
  db:
    build: ./mysql
    restart: always
    command: 
      - --default-authentication-plugin=mysql_native_password
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: userapi
      MYSQL_DATABASE: userapi
      MYSQL_USER: userapi
      MYSQL_PASSWORD: userapi
      MYSQL_ROOT_HOST: '%'
  api:
    build: ./device-api
    environment:
      DB_URI: db
      DB_NAME: userapi
      DB_USERNAME: userapi
      DB_PASSWORD: userapi
    ports:
      - 3000:3000
    links:
      - "db:database"
    depends_on:
      - db