kind: Service
apiVersion: v1
metadata:
  name: device-api
  namespace: default
  labels:
    app: device-api
spec:
  type: ClusterIP
  selector:
    app: device-api
  ports:
  - name: http
    port: 80
    targetPort: app-port